$dir = "D:\GITHUB项目\XY-Music-PC\Assets"

# wrong-named files generated by the buggy run (pixel size used as scale suffix)
$garbage = @(
    "Square44x44Logo.scale-44.png", "Square44x44Logo.scale-55.png", "Square44x44Logo.scale-66.png",
    "Square44x44Logo.scale-88.png", "Square44x44Logo.scale-176.png",
    "Square150x150Logo.scale-188.png", "Square150x150Logo.scale-225.png", "Square150x150Logo.scale-300.png", "Square150x150Logo.scale-600.png",
    "StoreLogo.scale-50.png", "StoreLogo.scale-63.png", "StoreLogo.scale-75.png",
    "SmallTile.scale-71.png", "SmallTile.scale-89.png", "SmallTile.scale-107.png", "SmallTile.scale-142.png", "SmallTile.scale-284.png",
    "LargeTile.scale-310.png", "LargeTile.scale-388.png", "LargeTile.scale-465.png", "LargeTile.scale-620.png", "LargeTile.scale-1240.png",
    "Wide310x150Logo.scale-310.png", "Wide310x150Logo.scale-388.png", "Wide310x150Logo.scale-465.png", "Wide310x150Logo.scale-620.png", "Wide310x150Logo.scale-1240.png",
    "SplashScreen.scale-620.png", "SplashScreen.scale-775.png", "SplashScreen.scale-930.png", "SplashScreen.scale-1240.png", "SplashScreen.scale-2480.png"
)
$removed = 0
foreach ($g in $garbage) {
    $p = Join-Path $dir $g
    if (Test-Path $p) { Remove-Item $p -Force; $removed++ }
}
Write-Output ("garbage removed: " + $removed)

# restore the 3 correctly-named files that were overwritten with wrong-size content
$restore = @("Square150x150Logo.scale-150.png", "StoreLogo.scale-100.png", "StoreLogo.scale-200.png")
foreach ($r in $restore) {
    $p = Join-Path $dir $r
    $bak = "$p.bak"
    if (Test-Path $bak) {
        Copy-Item $bak $p -Force
        Write-Output ("restored from backup: " + $r)
    } else {
        Write-Output ("NO BACKUP for " + $r)
    }
}

Write-Output "=== remaining icon files sanity ==="
Get-ChildItem $dir -Filter "*.png" | Where-Object { $_.Name -notmatch "^Album|^Artist|^Music|^default_cover|^hr|^Spectrum" } | Select-Object Name, Length | Format-Table -AutoSize
